name: Scheduler for scraping google news
  
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions: write-all


env:
  GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}

jobs:
  run-data-collection:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Upgrade pip
        run: pip install --upgrade pip
        
      - name: Install required modules
        run: pip install -r requirement_packages_for_news_scraping.txt

      - name: Run data collection script
        run: news_data.py
        
      - name: Adding user identity (email)
        run: git config --global user.email "saurabhdeosarkar100@gmail.com"
        
      - name: Adding user identity (username)
        run: git config --global user.name "Saura1996"
        
      - name: Add file to git
        run: git add news.json
      
      - name: Git commit
        run: git commit -m "Added/ updated news.json file"
        
      - name: Push changes
        run: git push origin main -f
